# Generated by Django 4.2.16 on 2024-12-05 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corps',
            old_name='code',
            new_name='numero',
        ),
    ]
