# Generated by Django 4.2.16 on 2024-12-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corps', '0002_rename_code_corps_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='corps',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdf_documents/'),
        ),
    ]
