# Generated by Django 4.2.16 on 2025-01-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corps', '0005_corpsstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='corps',
            name='telechargements',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='corps',
            name='visits',
            field=models.PositiveIntegerField(default=0, verbose_name='nombre de visite'),
        ),
    ]
