# Generated by Django 4.2.16 on 2025-02-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corps', '0006_corps_telechargements_corps_visits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corps',
            name='nom',
            field=models.CharField(blank=True, choices=[('Administration Publique', 'Administration Publique'), ('Administration Judiciaire', 'Administration Judiciaire'), ('Administration Pénitentiaire', 'Administration Pénitentiaire'), ('Agriculture-Elevage-Pêche', 'Agriculture-Elevage-Pêche'), ('Chercheur enseignant et Enseignement chercheur', 'Chercheur Enseignant et Enseignement chercheur'), ('Communication médiatisée', 'Communication médiatisée'), ('Diplomatie', 'Diplomatie'), ('Domaine-Topographie', 'Domaine-Topographie'), ('Environnement Eaux et Forêts', 'Environnement Eaux et Forêts'), ('Éducation de base et Enseignement secondaire', 'Éducation de base et Enseignement secondaire'), ('Énergie, Mines et Ressources', 'Énergie-Mines-Ressources'), ('Économie, Finances et Plan', 'Économie, Finances et Plan'), ('Inspection de l’Etat', 'Inspection de l’Etat'), ('Forces Armées', 'Forces Armées'), ('Jeunesse et Sports', 'Jeunesse et Sports'), ('Météorologie', 'Météorologie'), ('Planification', 'Planification'), ('Police nationale', 'Police nationale'), ('Poste et Télécommunications', 'Poste et Télécommunications'), ('Travail et Lois Sociales', 'Travail et Lois Sociales'), ('Corps transversaux', 'Corps transversaux'), ('Travaux publics, Habitat et Aménagement', 'Travaux publics, Habitat et Aménagement'), ('Transports', 'Transports'), ('Santé Publique', 'Santé Publique')], max_length=255, null=True),
        ),
    ]
