# Generated by Django 4.2.16 on 2025-01-25 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_visit_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='session_id',
        ),
    ]
