# Generated by Django 4.2.16 on 2025-01-30 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0004_visit_visit_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='visit_date',
        ),
    ]
