# Generated by Django 4.2.16 on 2025-01-30 17:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0005_remove_visit_visit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='visit_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
