# Generated by Django 4.2.16 on 2024-12-04 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('constitution', 'Constitution'), ('traité internationaux', 'Traité Internationaux'), ('convention', 'Convention'), ('lois organiques', 'Lois Organiques'), ('lois ordinaires', 'Lois Ordinaires'), ('ordonnances', 'Ordonnances'), ('decrets', 'Décrets'), ('arretes interministeriels', 'Arrêtés Interministériels'), ('arretes', 'Arrêtés'), ('circilaire', 'Circulaire'), ('notes', 'Notes')], max_length=50)),
                ('objet', models.TextField()),
                ('numero', models.TextField()),
                ('date', models.DateField()),
                ('conseil', models.CharField(choices=[('aucun', 'Aucun'), ('ministre', 'Ministre'), ('gouvernement', 'Gouvernement')], default='aucun', max_length=50)),
                ('fichier', models.FileField(upload_to='documents/')),
                ('status', models.CharField(choices=[('en_vigueur', 'En vigueur'), ('abroge', 'Abrogé')], default='en_vigueur', max_length=10)),
                ('domaine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.domaine')),
            ],
        ),
    ]
