# Generated by Django 4.2.16 on 2024-12-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['objet'], name='documents_d_objet_dc818a_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['numero'], name='documents_d_numero_d33edc_idx'),
        ),
    ]
