# Generated by Django 4.2.16 on 2024-12-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_documents_d_objet_dc818a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/pdf/'),
        ),
    ]
