# Generated by Django 4.2.16 on 2024-12-10 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='pdf_file',
        ),
    ]
