# Generated by Django 4.2.16 on 2024-12-14 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_document_pdf_file'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='document',
            name='documents_d_objet_dc818a_idx',
        ),
        migrations.RemoveIndex(
            model_name='document',
            name='documents_d_numero_d33edc_idx',
        ),
    ]
