# Generated by Django 4.2.16 on 2024-12-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_document_documents_d_objet_dc818a_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conseil', models.CharField(choices=[('CONSEIL DE MINISTRE', 'Ministre'), ('CONSEIL DE GOUVERNEMENT', 'Gouvernement')], default='CONSEIL DE GOUVERNEMENT', max_length=50)),
                ('titre', models.CharField(max_length=200)),
                ('texte', models.TextField()),
            ],
        ),
    ]
