# Generated by Django 4.2.16 on 2024-12-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_alter_actualite_conseil'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualite',
            name='date',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AddField(
            model_name='actualite',
            name='lieu',
            field=models.CharField(default=2001, max_length=100),
            preserve_default=False,
        ),
    ]
