# Generated by Django 4.2.16 on 2025-01-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_actualite_date_actualite_lieu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
