# Generated by Django 4.2.16 on 2025-01-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('constitution', 'Constitution'), ('traités internationaux', 'Traités Internationaux'), ('convention', 'Convention'), ('lois organiques', 'Lois Organiques'), ('lois ordinaires', 'Lois Ordinaires'), ('ordonnances', 'Ordonnances'), ('decrets', 'Décrets'), ('arretes interministeriels', 'Arrêtés Interministériels'), ('arretes', 'Arrêtés'), ('circilaire', 'Circulaire'), ('notes', 'Notes')], max_length=50),
        ),
    ]
