# Generated by Django 4.2.16 on 2025-01-15 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_alter_document_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domaine',
            options={'ordering': []},
        ),
    ]
