# Generated by Django 4.2.16 on 2025-01-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0018_alter_actualite_conseil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualite',
            name='conseil',
            field=models.CharField(choices=[('CONSEIL DES MINISTRES', 'Ministre'), ('CONSEIL DU GOUVERNEMENT', 'Gouvernement')], default='CONSEIL DES MINISTRES', max_length=50),
        ),
    ]
