# Generated by Django 4.2.16 on 2025-01-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0019_alter_actualite_conseil'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalOfficiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.TextField()),
                ('page', models.TextField()),
                ('date_creation', models.DateField()),
                ('fichier', models.FileField(upload_to='documents/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdf_documents/')),
            ],
        ),
    ]
