# Generated by Django 4.2.16 on 2025-01-20 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0020_journalofficiel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JournalOfficiel',
        ),
    ]
