# Generated by Django 4.2.16 on 2025-01-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0021_delete_journalofficiel'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='date_journal',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='inclus_journal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='numero_journal',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='page_journal',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
