# Generated by Django 4.2.16 on 2025-01-26 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0023_documentstats'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='document',
            new_name='objet_idx',
            old_name='documents_d_objet_dc818a_idx',
        ),
        migrations.RenameIndex(
            model_name='document',
            new_name='numero_idx',
            old_name='documents_d_numero_d33edc_idx',
        ),
    ]
