# Generated by Django 4.2.16 on 2025-01-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0024_rename_documents_d_objet_dc818a_idx_objet_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='visits',
            field=models.PositiveIntegerField(default=0, verbose_name='nombre de visite'),
        ),
    ]
