# Generated by Django 4.2.16 on 2025-01-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0025_document_visits'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='telechargements',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='document',
            name='conseil',
            field=models.CharField(choices=[('Autre', 'Autre'), ('ministre', 'Ministre'), ('gouvernement', 'Gouvernement')], default='Autre', max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('En vigueur', 'En vigueur'), ('Abrogé', 'Abrogé')], default='En vigueur', max_length=10),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('Constitution', 'Constitution'), ('Traités internationaux', 'Traités Internationaux'), ('Convention', 'Convention'), ('Lois organiques', 'Lois Organiques'), ('Lois ordinaires', 'Lois Ordinaires'), ('Ordonnances', 'Ordonnances'), ('Décrets', 'Décrets'), ('Arrêtés interministeriels', 'Arrêtés Interministériels'), ('Arrêtés', 'Arrêtés'), ('Circilaire', 'Circulaire'), ('Notes', 'Notes')], max_length=50),
        ),
    ]
